version: "3.8"

volumes:
  grafana_data:
  influxdb_data:

services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ROOT_URL=http://localhost

      # https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-in-the-docker-container
      - GF_INSTALL_PLUGINS=flant-statusmap-panel 0.5.1, snuids-trafficlights-panel 1.5.1

      # https://grafana.com/docs/grafana/latest/administration/image_rendering/#run-in-docker
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug

      # https://grafana.com/docs/grafana/latest/administration/configuration/#live
      - GF_LIVE_MAX_CONNECTIONS=0

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      # https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/monitoring/
      # https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/#other-available-settings
      - ENABLE_METRICS=true
    restart: always

  influxdb:
    image: influxdb:latest
    restart: always
    ports:
    - "8086:8086"
    volumes:
    - influxdb_data:/var/lib/influxdb

  nginx:
    image: nginx:latest
    restart: always
    environment:
      - TARGET_SERVICE=grafana:3000
    ports:
      - 80:80
    depends_on:
      - grafana
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
